class EventError(Exception):
    pass
class AuthError(Exception):
    pass
